version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # ===== Bug Detection =====
    - errcheck           # Check error returns are handled
    - govet              # Official Go vet checks
    - staticcheck        # Comprehensive static analysis
    - ineffassign        # Detect ineffective assignments
    - unused             # Find unused code
    - bodyclose          # Ensure HTTP response bodies are closed
    - noctx              # Check context usage in HTTP requests
    - nilerr             # Check nil errors are returned properly
    - nilnil             # Check for nil return with nil error
    - contextcheck       # Check context propagation
    - durationcheck      # Detect duration multiplication issues
    - makezero           # Find slice append issues
    - wastedassign       # Find wasted assignments

    # ===== Code Style =====
    - misspell           # Spelling mistakes
    - unconvert          # Unnecessary type conversions
    - whitespace         # Whitespace issues

    # ===== Code Quality =====
    - gocritic           # Comprehensive checks
    - gocyclo            # Cyclomatic complexity
    - gocognit           # Cognitive complexity
    - nakedret           # Naked returns in long functions
    - prealloc           # Slice preallocation suggestions
    - predeclared        # Shadowing predeclared identifiers
    - nestif             # Deeply nested ifs
    - goconst            # Repeated strings to constants
    - unparam            # Unused parameters
    - errname            # Error naming conventions
    - errorlint          # Error wrapping issues

    # ===== Security (runs separately in CI for detailed output) =====
    # - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 5

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  errorlint:
    errorf: true
    errorf-multi: true
    asserts: true
    comparison: true

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes: github.com/txn2/txeh

issues:
  exclude-rules:
    # Relax rules for tests
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - gocognit
        - gocyclo
        - misspell
        - unparam

    # Allow longer functions in cmd/
    - path: cmd/
      linters:
        - gocyclo
        - gocognit

    # Generated files
    - path: generated
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
