# Build customization
builds:
  - id: txeh
    # Path to main.go file.
    # Default is `main.go`
    main: ./txeh/txeh.go
    binary: txeh

    env:
    - CGO_ENABLED=0

    # GOOS list to build in.
    # For more info refer to https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux
    goos:
    - linux
    - darwin
    - windows

    # GOARCH to build in.
    # For more info refer to https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64
    goarch:
    - amd64
    - arm
    - arm64

    goarm:
    - "6"
    - "7"

    ldflags: "-s -w -X github.com/txn2/txeh/txeh/cmd.Version={{.Version}}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

release:
  github:
    owner: txn2
    name: txeh
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/txn2/txeh
    description: Etc Hosts Management Utility.
    maintainer: Craig Johnston <cjimti@gmail.com>
    license: Apache 2.0
    vendor: https://github.com/txn2
    formats:
      - apk
      - deb
      - rpm


archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: txeh
    tap:
      owner: txn2
      name: homebrew-tap
    commit_author:
      name: Craig Johnston
      email: cjimti@gmail.com
    folder: Formula
    homepage: https://github.com/txn2/txeh
    description: "Etc Hosts Management Utility."
    skip_upload: false
    test: |-
      txeh version

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Etc Hosts Management Utility.
    description: |
      Kubernetes bulk port forwarding utility.
    grade: stable
    confinement: classic
